In [1]:
import pandas as pd
import numpy as np

In [2]:
subscriptions = pd.read_csv("subscriptions.csv")
usage = pd.read_csv("usage.csv")

In [3]:
subscriptions.head()

,customer_id,signup_date,plan_type,plan_tier,monthly_price,acquisition_channel,primary_device,age_group,churned,churn_date,cancel_reason
0,1,2024-09-11,monthly,basic,12.99,promo_offer,android,45-54,yes,2025-06-29,technical_issues
1,2,2025-08-14,annual,basic,9.74,promo_offer,web,45-54,no,NaN,NaN
2,3,2025-01-24,monthly,basic,12.99,referral,ios,55+,no,NaN,NaN
3,4,2024-08-15,monthly,basic,12.99,paid_social,ios,25-34,yes,2024-08-20,not_using_enough
4,5,2025-06-24,annual,plus,14.99,paid_social,android,55+,no,NaN,NaN

In [4]:
usage.head()

,customer_id,month,workouts_completed,minutes_active,classes_booked,support_tickets
0,1,2024-09,5,140.0,0,0
1,1,2024-10,4,116.0,0,0
2,1,2024-11,7,208.0,0,0
3,1,2024-12,5,109.0,0,0
4,1,2025-01,1,41.0,0,0

In [5]:
subscriptions.isnull().sum()

customer_id               0
signup_date               0
plan_type                 0
plan_tier                 0
monthly_price             0
acquisition_channel       0
primary_device            0
age_group                 0
churned                   0
churn_date             2432
cancel_reason          2814
dtype: int64

In [6]:
usage.isnull().sum()

customer_id             0
month                   0
workouts_completed      0
minutes_active        506
classes_booked          0
support_tickets         0
dtype: int64

In [7]:
subscriptions.describe()

       customer_id  monthly_price
count  4200.000000    4200.000000
mean   2100.500000      16.742024
std    1212.579894       6.097368
min       1.000000       9.740000
25%    1050.750000      12.990000
50%    2100.500000      14.990000
75%    3150.250000      19.990000
max    4200.000000      29.990000

In [8]:
usage.describe()

,customer_id,workouts_completed,minutes_active,classes_booked,support_tickets
count,30685.000000,30685.000000,30179.000000,30685.000000,30685.000000
mean,2108.974189,4.464722,134.047218,0.724393,0.128304
std,1205.740007,4.096791,131.166001,1.432328,0.370582
min,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1060.000000,1.000000,40.000000,0.000000,0.000000
50%,2122.000000,3.000000,100.000000,0.000000,0.000000
75%,3143.000000,6.000000,189.000000,1.000000,0.000000
max,4200.000000,48.000000,1653.000000,16.000000,4.000000

In [9]:
subscriptions.shape

(4200, 11)

In [10]:
usage.shape

(30685, 6)

In [11]:
subscriptions.dtypes

customer_id              int64
signup_date                str
plan_type                  str
plan_tier                  str
monthly_price          float64
acquisition_channel        str
primary_device             str
age_group                  str
churned                    str
churn_date                 str
cancel_reason              str
dtype: object

In [12]:
usage.dtypes

customer_id             int64
month                     str
workouts_completed      int64
minutes_active        float64
classes_booked          int64
support_tickets         int64
dtype: object

In [13]:
subscriptions.duplicated().sum()

np.int64(0)

In [14]:
usage.duplicated().sum()

np.int64(160)

In [15]:
subscriptions["customer_id"].duplicated().sum()

np.int64(0)

In [16]:
categorical_cols = [
    "plan_type",
    "plan_tier",
    "acquisition_channel",
    "primary_device",
    "age_group",
    "churned",
    "cancel_reason"
]
for col in categorical_cols:
    print(f"\n{col}:")
    print(subscriptions[col].value_counts(dropna=False))

plan_type:
plan_type
monthly    2661
annual     1539
Name: count, dtype: int64

plan_tier:
plan_tier
basic      1929
plus       1462
premium     708
Basic        47
Plus         39
Premium      15
Name: count, dtype: int64

acquisition_channel:
acquisition_channel
organic        1298
paid_social     989
promo_offer     949
referral        488
partner         476
Name: count, dtype: int64

primary_device:
primary_device
ios        1976
android    1550
web         674
Name: count, dtype: int64

age_group:
age_group
25-34    1400
35-44    1073
18-24     717
45-54     619
55+       391
Name: count, dtype: int64

churned:
churned
no     2432
yes    1768
Name: count, dtype: int64

cancel_reason:
cancel_reason
NaN                  2814
not_using_enough      570
too_expensive         322
found_alternative     175
other                 162
technical_issues      157
Name: count, dtype: int64

In [17]:
subscriptions.isna().sum()

customer_id               0
signup_date               0
plan_type                 0
plan_tier                 0
monthly_price             0
acquisition_channel       0
primary_device            0
age_group                 0
churned                   0
churn_date             2432
cancel_reason          2814
dtype: int64

In [18]:
usage.isna().sum()

customer_id             0
month                   0
workouts_completed      0
minutes_active        506
classes_booked          0
support_tickets         0
dtype: int64

In [19]:
print("\nDate ranges:")
print("Signup:", subscriptions["signup_date"].min(), "to", subscriptions["signup_date"].max())
print("Churn:", subscriptions["churn_date"].min(), "to", subscriptions["churn_date"].max())

Date ranges:
Signup: 2024-07-01 to 2025-10-30
Churn: 2024-07-02 to 2025-12-31

In [20]:
print("\nNegative values:")
numeric_usage = ["workouts_completed", "minutes_active",
                 "classes_booked", "support_tickets"]

for col in numeric_usage:
    print(col, ":", (usage[col] < 0).sum())

Negative values:
workouts_completed : 0
minutes_active : 0
classes_booked : 0
support_tickets : 0

In [21]:
subscriptions["plan_tier"] = subscriptions["plan_tier"].str.lower()

In [22]:
usage[usage.duplicated(subset=["customer_id", "month"], keep=False)].sort_values(
    ["customer_id", "month"]
)

,customer_id,month,workouts_completed,minutes_active,classes_booked,support_tickets
286,44,2025-11,0,0.0,0,0
22367,44,2025-11,0,0.0,0,0
570,89,2024-12,5,206.0,3,0
7619,89,2024-12,5,206.0,3,0
757,116,2025-08,8,273.0,4,0
...,...,...,...,...,...,...
29668,4063,2024-10,3,101.0,1,0
266,4069,2025-12,3,92.0,0,0
29704,4069,2025-12,3,92.0,0,0
7749,4167,2025-01,2,59.0,0,0
30440,4167,2025-01,2,59.0,0,0

In [23]:
usage.duplicated(subset=["customer_id", "month"]).sum()

np.int64(160)

In [24]:

usage.duplicated().sum()

np.int64(160)

In [25]:
usage = usage.drop_duplicates()

In [26]:
usage.duplicated().sum()

np.int64(0)

In [27]:
usage.duplicated(subset=["customer_id", "month"]).sum()

np.int64(0)

In [28]:
subscriptions.groupby("churned")["churn_date"].apply(lambda x: x.isna().sum())

churned
no     2432
yes       0
Name: churn_date, dtype: int64

In [29]:
subscriptions.groupby("churned")["cancel_reason"].apply(
    lambda x: x.isna().sum()
)

churned
no     2432
yes     382
Name: cancel_reason, dtype: int64

In [30]:
usage[usage["minutes_active"].isna()].head(10)

,customer_id,month,workouts_completed,minutes_active,classes_booked,support_tickets
22,5,2025-11,0,NaN,0,0
33,7,2024-12,3,NaN,0,0
61,11,2025-10,9,NaN,0,0
81,14,2025-08,7,NaN,0,1
203,31,2025-03,0,NaN,0,1
386,60,2025-07,7,NaN,2,0
396,61,2025-08,1,NaN,0,1
418,66,2025-01,2,NaN,0,0
536,81,2025-09,0,NaN,0,0
605,92,2025-10,2,NaN,0,0

In [31]:
usage.groupby(usage["minutes_active"].isna())["workouts_completed"].mean()

minutes_active
False    4.467724
True     4.322068
Name: workouts_completed, dtype: float64

In [32]:
usage["minutes_active"].isna().sum()

np.int64(503)

In [33]:
print("Rows:", usage.shape[0])
print("Missing minutes:", usage["minutes_active"].isna().sum())
print("Exact duplicates:", usage.duplicated().sum())

Rows: 30525
Missing minutes: 503
Exact duplicates: 0

In [34]:
usage['minutes_active'].isna().mean()*100

np.float64(1.647829647829648)

In [35]:
usage.groupby(usage["minutes_active"].isna())["workouts_completed"].agg(
    ["count", "mean", "min", "max"]
)

                count      mean  min  max
minutes_active
False           30022  4.467724    0   48
True              503  4.322068    0   26

In [36]:
usage[usage["minutes_active"].isna()]["workouts_completed"].value_counts().sort_index()

workouts_completed
0     55
1     72
2     65
3     68
4     47
5     36
6     49
7     31
8     23
9     13
10    11
11     9
12     7
13     1
14     4
15     3
17     4
21     2
22     1
23     1
26     1
Name: count, dtype: int64

In [38]:
subscriptions['signup_date'] = pd.to_datetime(subscriptions['signup_date'])

In [39]:
subscriptions["churn_date"] = pd.to_datetime(
    subscriptions["churn_date"]
)

In [40]:
subscriptions[["signup_date", "churn_date"]].dtypes

signup_date    datetime64[us]
churn_date     datetime64[us]
dtype: object

In [41]:
usage["month"].dtype

In [42]:
print("Subscriptions:", subscriptions.shape)
print("Usage:", usage.shape)

print("\nMissing values in subscriptions:")
print(subscriptions.isna().sum())

print("\nMissing values in usage:")
print(usage.isna().sum())

Subscriptions: (4200, 11)
Usage: (30525, 6)

Missing values in subscriptions:
customer_id               0
signup_date               0
plan_type                 0
plan_tier                 0
monthly_price             0
acquisition_channel       0
primary_device            0
age_group                 0
churned                   0
churn_date             2432
cancel_reason          2814
dtype: int64

Missing values in usage:
customer_id             0
month                   0
workouts_completed      0
minutes_active        503
classes_booked          0
support_tickets         0
dtype: int64

In [44]:
from sqlalchemy import create_engine

username = "root"
password = "root"
host = "localhost"
port = "3306"
database = "customer_churn_analysis"

engine = create_engine(
    f"mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}"
)
table_name = "subscriptions"

subscriptions.to_sql(
    name=table_name,
    con=engine,
    if_exists="replace",
    index=False
)

table_name = "usage"

usage.to_sql(
    name=table_name,
    con=engine,
    if_exists="replace",
    index=False
)

-1

In [ ]:
from sqlalchemy import inspect

inspector = inspect(engine)
print(inspector.get_table_names())